name: kuama_dart_domain
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  convert: ^3.0.0

  logging: ^1.0.1

  rxdart: ^0.26.0
  dartz: ^0.10.0-nullsafety.2
  built_value: ^8.0.6
  built_collection: ^5.0.0
  equatable: ^2.0.2

  get_it: ^7.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
