name: kuama_dart_domain
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  convert: ^3.0.0

  logging: ^1.0.0

  rxdart: ^0.27.0
  dartz: ^0.10.0-nullsafety.2
  built_value: ^8.0.0
  built_collection: ^5.0.0
  equatable: ^2.0.0

  get_it: ^7.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test:

  index_generator: ^2.0.1

# To generate index files: flutter pub run index_generator:main
index_generator:
  filters:
    # Ignore all private folders or files
    - black: .*\/_.*\/.*
    - black: .*\/_.*.dart*
  indexes:
    - path: lib
      name: permissions
      library: kuama_dart_permissions
      export:
        - src/features/permissions